### ISSUE TITLE
Warning Django 1.9

### ISSUE THREAD

**Issue by SalahAdDin** [django-compressor/django-appconf#17]
Please, update your app, now we have this warning:
```
/home/tulipan/Proyectos/TiempoTurco/lib/python3.4/importlib/_bootstrap.py:321: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  return f(*args, **kwds)
```

**Comment by carltongibson** [comment]
I'm going to close this as per the discussion on #18: Django 1.8 requires Python 2.7; AppConf conditionally imports `importlib` from the standard library and will never trigger the `RemovedInDjango19Warning` here. 

I am **very happy** to re-open this if we can see a full traceback showing that the issue is in fact to do with AppConf.
