### ISSUE TITLE
AppConf subclass settings disappear in second and subsequent uses of override_settings

### ISSUE THREAD

**Issue by mhl** [django-compressor/django-appconf#30]
(This might be related to #29 but since the symptoms are different I'm creating a new issue.)

If you've added settings using a subclass of `AppConf` from a Django application, it seems that those settings are available in the first `override_settings`-wrapped method, but not in subsequent ones.

I created a minimal django project to demonstrate this, which you can clone from here: https://github.com/mhl/django-appconf-test

The AppConf subclass, which is used in the only view, is:

```python
class ExampleExtraConf(AppConf):
    MY_EXTRA_SETTING = 'foo'
```

... and the two (identical) tests are:

```python
from django.test import TestCase
from django.test.utils import override_settings


class ExampleTests(TestCase):

    @override_settings(MEDIA_ROOT='/var/tmp/')
    def test_once(self):
        response = self.client.get('/')
        self.assertContains(response, 'foo')

    @override_settings(MEDIA_ROOT='/var/tmp/')
    def test_twice(self):
        response = self.client.get('/')
        self.assertContains(response, 'foo')
```

You'll find that `test_once` passes, but `test_twice` fails:

```
 ./manage.py test
Creating test database for alias 'default'...
.E
======================================================================
ERROR: test_twice (myproject.tests.ExampleTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mark/.virtualenvs/minimal-django-test-project/local/lib/python2.7/site-packages/django/test/utils.py", line 196, in inner
    return test_func(*args, **kwargs)
  File "/home/mark/minimal-django-test-project/myproject/tests.py", line 14, in test_twice
    response = self.client.get('/')
  File "/home/mark/.virtualenvs/minimal-django-test-project/local/lib/python2.7/site-packages/django/test/client.py", line 500, in get
    **extra)
  File "/home/mark/.virtualenvs/minimal-django-test-project/local/lib/python2.7/site-packages/django/test/client.py", line 303, in get
    return self.generic('GET', path, secure=secure, **r)
  File "/home/mark/.virtualenvs/minimal-django-test-project/local/lib/python2.7/site-packages/django/test/client.py", line 379, in generic
    return self.request(**r)
  File "/home/mark/.virtualenvs/minimal-django-test-project/local/lib/python2.7/site-packages/django/test/client.py", line 466, in request
    six.reraise(*exc_info)
  File "/home/mark/.virtualenvs/minimal-django-test-project/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mark/minimal-django-test-project/example/views.py", line 7, in homepage
    settings.EXAMPLE_MY_EXTRA_SETTING
  File "/home/mark/.virtualenvs/minimal-django-test-project/local/lib/python2.7/site-packages/django/conf/__init__.py", line 49, in __getattr__
    return getattr(self._wrapped, name)
  File "/home/mark/.virtualenvs/minimal-django-test-project/local/lib/python2.7/site-packages/django/conf/__init__.py", line 160, in __getattr__
    return getattr(self.default_settings, name)
AttributeError: 'Settings' object has no attribute 'EXAMPLE_MY_EXTRA_SETTING'

----------------------------------------------------------------------
Ran 2 tests in 0.045s

FAILED (errors=1)
Destroying test database for alias 'default'...
```

---

To help people who find this via Google, we came across this when finding that the [django-statici18n](https://django-statici18n.readthedocs.org/en/latest/)  `statici18n` template tag was failing in some tests where `override_settings` was used, producing a traceback like:

```
  File "/home/mark/.virtualenvs/ynr-popolo-upstream/local/lib/python2.7/site-packages/django/template/base.py", line 1197, in render
    return func(*resolved_args, **resolved_kwargs)
  File "/home/mark/.virtualenvs/ynr-popolo-upstream/local/lib/python2.7/site-packages/statici18n/templatetags/statici18n.py", line 34, in statici18n
    return static(get_path(locale))
  File "/home/mark/.virtualenvs/ynr-popolo-upstream/local/lib/python2.7/site-packages/statici18n/templatetags/statici18n.py", line 21, in get_path
    return os.path.join(settings.STATICI18N_OUTPUT_DIR,
  File "/home/mark/.virtualenvs/ynr-popolo-upstream/local/lib/python2.7/site-packages/django/conf/__init__.py", line 49, in __getattr__
    return getattr(self._wrapped, name)
  File "/home/mark/.virtualenvs/ynr-popolo-upstream/local/lib/python2.7/site-packages/django/conf/__init__.py", line 160, in __getattr__
    return getattr(self.default_settings, name)
AttributeError: 'Settings' object has no attribute 'STATICI18N_OUTPUT_DIR'
```

**Comment by hellysmile** [comment]
I have absolutely same problem

**Comment by carltongibson** [comment]
OK. Thanks for the report. I'll have a look at this over the holiday period. (PRs welcome in the meantime.)

**Comment by sergei-maertens** [comment]
I'm running into this issue as well, what's the status of this ticket?

**Comment by carltongibson** [comment]
Unchanged. Root cause analyses or PRs welcome.

**Comment by sergei-maertens** [comment]
It seems that the root cause is that `override_settings` instantiates a `django.conf.UserSettingsHolder`, initialized with `django.conf.settings._wrapped`, causing the actual settings object no longer to be 'patched' with the django-appconf settings.

I'm seeing that `override_settings` does fire a `setting_changed` signal, so we might be able to hook into that. I'll get a proof of concept working and try to get back at you asap.

**Comment by sergei-maertens** [comment]
Update: root cause found, and it's actually documented in this project, and I quote:

> AppConf classes depend on being imported during startup of the Django process. Even though there are multiple modules loaded automatically, only the models modules (usually the models.py file of your app) are guaranteed to be loaded at startup. Therefore it's recommended to put your AppConf subclass(es) there, too.

The issue at hand was caused by a templatetag for me as well. Since it's a library that doesn't have models, only a management command and a templatetag, the settings were loaded too late. So, when Django configures the `override_settings` object, it has never heard of your `AppConf` settings yet.

Because of the way that `AppConf` works, it's not targeting the correct object to add the settings to when it finally gets imported, leading to these errors.

The solution is very easy for this, you can use django's own `AppConfig`. Example:
```
# systemjs.apps
from __future__ import absolute_import, unicode_literals

from django.apps import AppConfig
from django.utils.translation import ugettext_lazy as _


class SystemJSConfig(AppConfig):
    name = 'systemjs'
    verbose_name = _('Django SystemJS')

    def ready(self):
        from . import conf  # noqa
```
Reference: https://docs.djangoproject.com/en/1.9/ref/applications/#for-application-authors

This ensures that the django default settings are patched by `AppConf` when starting up the tests, leading to `@override_settings` knowing of these settings before the patching starts.

I think this is only relevant for Django < 1.9, since the custom template tag libraries are loaded on startup time now, instead of when they're actually called in a template via `{% load %}`.

**Comment by carltongibson** [comment]
Good. Yes. And that all makes sense. I'm going to leave this open for now to remind me to have a think about it.

**Comment by sergei-maertens** [comment]
Might be interesting to build in an `autodiscover` feature just like the admin, and run it in the `AppConfig.ready` hook. Other than that, I think a small modification to the README should be enough (mention AppConfig).

**Comment by millerdev** [comment]
Also seeing the same issue here.

**Comment by carltongibson** [comment]
https://github.com/django-compressor/django-appconf/pull/34/commits/71c2f9397bb24709ee0004e1a4481002e99da8a9 adds a couple of tests checking the `override_settings` compat. — they both pass. 

I think @sergei-maertens  is right: the problem is the AppConf subclass not getting loaded. 

@mhl I looked at your example project. There's no models and no (Django) AppConf either — if you add the latter and import you (AppConf) AppConf there does your problem go away? 

I'm going to close this as "Cannot Reproduce". 

I'm very happy to look again if anyone can add a failing test to the AppConf test suite.

**Comment by jedie** [comment]
Seems that i have the same Problem, see: https://github.com/django-haystack/django-haystack/issues/1493

Test code, e.g.:
```
@override_settings(DEBUG=False)
class WithoutDebugTest(ClientBaseTestCase):
    def test_robots(self):
        response = self.client.get("/robots.txt")
        self.assertIn('Allow: /\n', response.content)


@override_settings(DEBUG=True)
class WithDebugTest(ClientBaseTestCase):
    def test_robots(self):
        response = self.client.get("/robots.txt")
        self.assertIn('Disallow: /\n', response.content)
```

Traceback:


```
...

/usr/lib/python2.7/importlib/__init__.py:37: in import_module
    __import__(name)
.venv/local/lib/python2.7/site-packages/_pytest/assertion/rewrite.py:216: in load_module
    py.builtin.exec_(co, mod.__dict__)
.venv/local/lib/python2.7/site-packages/celery_haystack/tasks.py:17: in <module>
    class CeleryHaystackSignalHandler(Task):
.venv/local/lib/python2.7/site-packages/celery_haystack/tasks.py:18: in CeleryHaystackSignalHandler
    using = settings.CELERY_HAYSTACK_DEFAULT_ALIAS
.venv/local/lib/python2.7/site-packages/django/conf/__init__.py:49: in __getattr__
    return getattr(self._wrapped, name)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <django.conf.UserSettingsHolder object at 0x7fc2dd035f90>
name = 'CELERY_HAYSTACK_DEFAULT_ALIAS'

    def __getattr__(self, name):
        if name in self._deleted:
            raise AttributeError
>       return getattr(self.default_settings, name)
E       AttributeError: 'Settings' object has no attribute 'CELERY_HAYSTACK_DEFAULT_ALIAS'

...
```

**Comment by carltongibson** [comment]
@jedie See the resolution on #29. Look at when you're pulling in `tasks` (for `CeleryHaystackSignalHandler`) When are you doing that? Is it before app loading is finished? If so move that code to a `ready()` handler.

**Comment by jedie** [comment]
Thanks! Seems it's a own made error, doing stuff before app loading finished. Sorry...

**Comment by jedie** [comment]
OK, now i have refactor a little bit and ran into the problem, again:
```
.venv/local/lib/python2.7/site-packages/cms/models/pagemodel.py:779: in publish
    cms_signals.post_publish.send(sender=Page, instance=self, language=language)
.venv/local/lib/python2.7/site-packages/django/dispatch/dispatcher.py:189: in send
    response = receiver(signal=self, sender=sender, **named)
.venv/local/lib/python2.7/site-packages/aldryn_search/receivers.py:17: in publish_cms_page
    add_to_index.send(sender=Title, instance=title, object_action='publish')
.venv/local/lib/python2.7/site-packages/django/dispatch/dispatcher.py:189: in send
    response = receiver(signal=self, sender=sender, **named)
.venv/local/lib/python2.7/site-packages/celery_haystack/signals.py:21: in enqueue_save
    return self.enqueue('update', instance, sender, **kwargs)
src/apps/cms_search/signals.py:46: in enqueue
    enqueue_task(action, instance, **kwargs)
.venv/local/lib/python2.7/site-packages/celery_haystack/utils.py:41: in enqueue_task
    task = get_update_task()
.venv/local/lib/python2.7/site-packages/celery_haystack/utils.py:17: in get_update_task
    mod = import_module(module)
/usr/lib/python2.7/importlib/__init__.py:37: in import_module
    __import__(name)
src/apps/cms_search/tasks.py:10: in <module>
    from celery_haystack.tasks import CeleryHaystackSignalHandler, IndexNotFoundException
.venv/local/lib/python2.7/site-packages/celery_haystack/tasks.py:17: in <module>
    class CeleryHaystackSignalHandler(Task):
.venv/local/lib/python2.7/site-packages/celery_haystack/tasks.py:18: in CeleryHaystackSignalHandler
    using = settings.CELERY_HAYSTACK_DEFAULT_ALIAS
```

Initial point is a `pytest.fixture` to create some default django cms pages.

EDIT: as a temporary work-a-round: I add the defaults into my settings:
```
CELERY_HAYSTACK_DEFAULT_ALIAS = None
CELERY_HAYSTACK_MAX_RETRIES = 1
CELERY_HAYSTACK_RETRY_DELAY = 5 * 60
```

**Comment by jedie** [comment]
> EDIT: as a temporary work-a-round: I add the defaults into my settings:

It only happens in the tests. That's why I have made a other solution. Because I want to keep my settings clean:

My currently new work-a-round is a `pytest.fixture(autouse=True)` and fill django settings with app-config settings manually, see: https://gist.github.com/jedie/c119e73d8e7dad48183f9622b430373f

This address my problems with django-imagekit here: https://github.com/matthewwithanm/django-imagekit/issues/251 But also fix the same problems with aldryn_search here: https://github.com/aldryn/aldryn-search/issues/86
