### ISSUE TITLE
Why not just using settings.py ?

### ISSUE THREAD

**Issue by lapinvert** [django-compressor/django-appconf#74]
I am sorry for this simple question. I was trying to figure out the use case for django-appconf, and basically for now I don't see it doing something that is already done by declaring your own custom settings in settings.py and re-use it everywhere.

Could somebody please explain to me what problem it solves that settings.py doesn't?

**Comment by ghost** [comment]
When you develop reusable apps, it is not ideal to put all your configurations into `settings.py` for two reasons:

1. The module belongs to the whole project, which may contains other configurations that belong to other apps.
2. Even if your project is built solely for a single app, you can't distribute `settings.py` without forcing users to tinkering and modifying the existing `settings.py` module in their own project, which is not an elegant solution.

According to the documentation, using [`AppConfig`](https://docs.djangoproject.com/en/3.1/ref/applications/#application-configuration) would solve the problem. I'm not going to speak for the `django-appconf` since I'm not the developer and I just discovered this app a couple hours ago.
